### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rev0zz** [natewong1313/recaptcha-fullauto#1]
Traceback (most recent call last):
  File "C:\recaptcha-fullauto\src\main.py", line 9, in <module>
    recaptcha_token = rcs.solve()
  File "C:\recaptcha-fullauto\src\recaptcha_solver.py", line 50, in solve
    self.switch_to_challenge_iframe()
  File "C:\recaptcha-fullauto\src\recaptcha_solver.py", line 85, in switch_to_challenge_iframe
    recaptcha_challenge_iframe = WebDriverWait(self.driver, 25).until(EC.visibility_of_element_located((By.CSS_SELECTOR, 'iframe[title="recaptcha challenge"]')))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

![image](https://user-images.githubusercontent.com/69242505/116093789-6b5b2880-a6c0-11eb-91cf-3b24130eea8b.png)

**Comment by rev0zz** [comment]
ok I think this only works in English, so an error occurs, I'll try to redo it in my language

**Comment by rev0zz** [comment]
since 20 attempts it worked

![image](https://user-images.githubusercontent.com/69242505/116097670-ca6e6c80-a6c3-11eb-93fe-ca076529ea97.png)
